rootProject.name = "CloudStreamFrenchAddons"
include("FrenchStreamProvider")
include("Movix")
include("FSTV")
include("FrenchManga")
include("DoTriv")
include("Frembed")
include("FrenchAnime")
include("FsMirrorLol")
include("JourFilm")
include("WiflixProvider")
